// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void FloatUp_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
void ui_event_Button101(lv_event_t * e);
lv_obj_t * ui_Button101;
lv_obj_t * ui_Label101;
void ui_event_Button102(lv_event_t * e);
lv_obj_t * ui_Button102;
lv_obj_t * ui_Label102;
lv_obj_t * ui_Button103;
lv_obj_t * ui_Label103;
lv_obj_t * ui_Button104;
lv_obj_t * ui_Label104;
void ui_event_Button201(lv_event_t * e);
lv_obj_t * ui_Button201;
lv_obj_t * ui_Label201;
lv_obj_t * ui_Button202;
lv_obj_t * ui_Label202;
lv_obj_t * ui_Button203;
lv_obj_t * ui_Label203;
lv_obj_t * ui_Button8;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Button9;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Button10;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Button11;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Button12;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Panel1;


// SCREEN: ui_Screen101
void ui_Screen101_screen_init(void);
lv_obj_t * ui_Screen101;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_LabelScreen101;
lv_obj_t * ui_FlameSensor;
lv_obj_t * ui_LabelFL101;
lv_obj_t * ui_LabelValueFL101;
void ui_event_FireImg101(lv_event_t * e);
lv_obj_t * ui_FireImg101;
lv_obj_t * ui_SmokeSensor;
lv_obj_t * ui_LabelMQ101;
lv_obj_t * ui_LabelValueMQ101;
void ui_event_SmokeImg101(lv_event_t * e);
lv_obj_t * ui_SmokeImg101;
lv_obj_t * ui_Switch101;
void ui_event_ButtonBack101(lv_event_t * e);
lv_obj_t * ui_ButtonBack101;
lv_obj_t * ui_ImgBack101;


// SCREEN: ui_Screen102
void ui_Screen102_screen_init(void);
lv_obj_t * ui_Screen102;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_LabelScreen102;
lv_obj_t * ui_FlameSensor102;
lv_obj_t * ui_LabelFL102;
lv_obj_t * ui_LabelValueFL102;
void ui_event_FireImg102(lv_event_t * e);
lv_obj_t * ui_FireImg102;
lv_obj_t * ui_SmokeSensor102;
lv_obj_t * ui_LabelMQ102;
lv_obj_t * ui_LabelValueMQ102;
void ui_event_SmokeImg102(lv_event_t * e);
lv_obj_t * ui_SmokeImg102;
lv_obj_t * ui_Switch102;
void ui_event_ButtonBack102(lv_event_t * e);
lv_obj_t * ui_ButtonBack102;
lv_obj_t * ui_ImgBack102;


// SCREEN: ui_Screen201
void ui_Screen201_screen_init(void);
lv_obj_t * ui_Screen201;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_LabelScreen201;
lv_obj_t * ui_FlameSensor201;
lv_obj_t * ui_LabelFL201;
lv_obj_t * ui_LabelValueFL201;
void ui_event_FireImg201(lv_event_t * e);
lv_obj_t * ui_FireImg201;
lv_obj_t * ui_SmokeSensor201;
lv_obj_t * ui_LabelMQ201;
lv_obj_t * ui_LabelValueMQ201;
void ui_event_SmokeImg201(lv_event_t * e);
lv_obj_t * ui_SmokeImg201;
lv_obj_t * ui_Switch201;
void ui_event_ButtonBack201(lv_event_t * e);
lv_obj_t * ui_ButtonBack201;
lv_obj_t * ui_ImgBack201;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void FloatUp_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 0, -100);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_in);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_y);
    lv_anim_start(&PropertyAnimation_0);

}


///////////////////// FUNCTIONS ////////////////////
void ui_event_Button101(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen101, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen101_screen_init);
    }
}
void ui_event_Button102(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen102, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen102_screen_init);
    }
}
void ui_event_Button201(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen201, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Screen201_screen_init);
    }
}
void ui_event_FireImg101(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FloatUp_Animation(ui_LabelValueFL101, 0);
    }
}
void ui_event_SmokeImg101(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FloatUp_Animation(ui_LabelValueMQ101, 0);
    }
}
void ui_event_ButtonBack101(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_FireImg102(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FloatUp_Animation(ui_LabelValueFL101, 0);
    }
}
void ui_event_SmokeImg102(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FloatUp_Animation(ui_LabelValueMQ101, 0);
    }
}
void ui_event_ButtonBack102(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_FireImg201(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FloatUp_Animation(ui_LabelValueFL101, 0);
    }
}
void ui_event_SmokeImg201(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        FloatUp_Animation(ui_LabelValueMQ101, 0);
    }
}
void ui_event_ButtonBack201(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui_Screen101_screen_init();
    ui_Screen102_screen_init();
    ui_Screen201_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
