// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0xB8DFE9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button101 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button101, 60);
    lv_obj_set_height(ui_Button101, 40);
    lv_obj_set_x(ui_Button101, -120);
    lv_obj_set_y(ui_Button101, -70);
    lv_obj_set_align(ui_Button101, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button101, lv_color_hex(0x217C69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button101, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button101, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button101, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button101, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label101 = lv_label_create(ui_Button101);
    lv_obj_set_width(ui_Label101, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label101, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label101, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label101, "101");

    ui_Button102 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button102, 60);
    lv_obj_set_height(ui_Button102, 40);
    lv_obj_set_x(ui_Button102, -40);
    lv_obj_set_y(ui_Button102, -70);
    lv_obj_set_align(ui_Button102, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button102, lv_color_hex(0x217C69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button102, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button102, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button102, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button102, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label102 = lv_label_create(ui_Button102);
    lv_obj_set_width(ui_Label102, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label102, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label102, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label102, "102");

    ui_Button103 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button103, 60);
    lv_obj_set_height(ui_Button103, 40);
    lv_obj_set_x(ui_Button103, 40);
    lv_obj_set_y(ui_Button103, -70);
    lv_obj_set_align(ui_Button103, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button103, lv_color_hex(0x217C69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button103, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button103, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button103, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button103, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label103 = lv_label_create(ui_Button103);
    lv_obj_set_width(ui_Label103, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label103, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label103, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label103, "103");

    ui_Button104 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button104, 60);
    lv_obj_set_height(ui_Button104, 40);
    lv_obj_set_x(ui_Button104, 120);
    lv_obj_set_y(ui_Button104, -70);
    lv_obj_set_align(ui_Button104, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button104, lv_color_hex(0x217C69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button104, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button104, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button104, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button104, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label104 = lv_label_create(ui_Button104);
    lv_obj_set_width(ui_Label104, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label104, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label104, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label104, "104");

    ui_Button201 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button201, 60);
    lv_obj_set_height(ui_Button201, 40);
    lv_obj_set_x(ui_Button201, -120);
    lv_obj_set_y(ui_Button201, -10);
    lv_obj_set_align(ui_Button201, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button201, lv_color_hex(0x217C69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button201, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button201, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button201, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button201, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label201 = lv_label_create(ui_Button201);
    lv_obj_set_width(ui_Label201, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label201, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label201, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label201, "201");

    ui_Button202 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button202, 60);
    lv_obj_set_height(ui_Button202, 40);
    lv_obj_set_x(ui_Button202, -40);
    lv_obj_set_y(ui_Button202, -10);
    lv_obj_set_align(ui_Button202, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button202, lv_color_hex(0x217C69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button202, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button202, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button202, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button202, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label202 = lv_label_create(ui_Button202);
    lv_obj_set_width(ui_Label202, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label202, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label202, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label202, "202");

    ui_Button203 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button203, 60);
    lv_obj_set_height(ui_Button203, 40);
    lv_obj_set_x(ui_Button203, 40);
    lv_obj_set_y(ui_Button203, -10);
    lv_obj_set_align(ui_Button203, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button203, lv_color_hex(0x217C69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button203, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button203, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button203, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button203, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label203 = lv_label_create(ui_Button203);
    lv_obj_set_width(ui_Label203, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label203, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label203, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label203, "203");

    ui_Button8 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button8, 60);
    lv_obj_set_height(ui_Button8, 40);
    lv_obj_set_x(ui_Button8, 120);
    lv_obj_set_y(ui_Button8, -10);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0x217C69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "204");

    ui_Button9 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button9, 60);
    lv_obj_set_height(ui_Button9, 40);
    lv_obj_set_x(ui_Button9, -120);
    lv_obj_set_y(ui_Button9, 50);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0x217C69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "301");

    ui_Button10 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button10, 60);
    lv_obj_set_height(ui_Button10, 40);
    lv_obj_set_x(ui_Button10, -40);
    lv_obj_set_y(ui_Button10, 50);
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0x217C69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "302");

    ui_Button11 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button11, 60);
    lv_obj_set_height(ui_Button11, 40);
    lv_obj_set_x(ui_Button11, 40);
    lv_obj_set_y(ui_Button11, 50);
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0x217C69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button11, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "303");

    ui_Button12 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button12, 60);
    lv_obj_set_height(ui_Button12, 40);
    lv_obj_set_x(ui_Button12, 120);
    lv_obj_set_y(ui_Button12, 50);
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x217C69), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button12, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Button12);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "304");

    ui_Label13 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, -105);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "APARTMENT");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 0);
    lv_obj_set_y(ui_Label14, 100);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "DATE");

    ui_Panel1 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel1, 150);
    lv_obj_set_height(ui_Panel1, 6);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 85);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x885B5B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xBDDEEE), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button101, ui_event_Button101, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button102, ui_event_Button102, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button201, ui_event_Button201, LV_EVENT_ALL, NULL);

}
