// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen102_screen_init(void)
{
    ui_Screen102 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen102, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen102, lv_color_hex(0xBDDEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen102, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen102);
    lv_obj_set_width(ui_Panel4, 64);
    lv_obj_set_height(ui_Panel4, 32);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, -100);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelScreen102 = lv_label_create(ui_Screen102);
    lv_obj_set_width(ui_LabelScreen102, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScreen102, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelScreen102, 0);
    lv_obj_set_y(ui_LabelScreen102, -100);
    lv_obj_set_align(ui_LabelScreen102, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScreen102, "102");
    lv_obj_set_style_text_font(ui_LabelScreen102, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FlameSensor102 = lv_obj_create(ui_Screen102);
    lv_obj_remove_style_all(ui_FlameSensor102);
    lv_obj_set_width(ui_FlameSensor102, 100);
    lv_obj_set_height(ui_FlameSensor102, 100);
    lv_obj_set_x(ui_FlameSensor102, -75);
    lv_obj_set_y(ui_FlameSensor102, -20);
    lv_obj_set_align(ui_FlameSensor102, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FlameSensor102, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FlameSensor102, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FlameSensor102, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FlameSensor102, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FlameSensor102, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FlameSensor102, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_FlameSensor102, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFL102 = lv_label_create(ui_FlameSensor102);
    lv_obj_set_width(ui_LabelFL102, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFL102, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelFL102, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelFL102, "Flame");

    ui_LabelValueFL102 = lv_label_create(ui_FlameSensor102);
    lv_obj_set_width(ui_LabelValueFL102, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValueFL102, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelValueFL102, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValueFL102, "Value");

    ui_FireImg102 = lv_img_create(ui_FlameSensor102);
    lv_img_set_src(ui_FireImg102, &ui_img_fire_border_resize_png);
    lv_obj_set_width(ui_FireImg102, 100);
    lv_obj_set_height(ui_FireImg102, 100);
    lv_obj_set_x(ui_FireImg102, 0);
    lv_obj_set_y(ui_FireImg102, 100);
    lv_obj_set_align(ui_FireImg102, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_FireImg102, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FireImg102, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_FireImg102, 180);

    ui_SmokeSensor102 = lv_obj_create(ui_Screen102);
    lv_obj_remove_style_all(ui_SmokeSensor102);
    lv_obj_set_width(ui_SmokeSensor102, 100);
    lv_obj_set_height(ui_SmokeSensor102, 103);
    lv_obj_set_x(ui_SmokeSensor102, 75);
    lv_obj_set_y(ui_SmokeSensor102, -20);
    lv_obj_set_align(ui_SmokeSensor102, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SmokeSensor102, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SmokeSensor102, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SmokeSensor102, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SmokeSensor102, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SmokeSensor102, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SmokeSensor102, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SmokeSensor102, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMQ102 = lv_label_create(ui_SmokeSensor102);
    lv_obj_set_width(ui_LabelMQ102, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMQ102, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelMQ102, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelMQ102, "Smoke");

    ui_LabelValueMQ102 = lv_label_create(ui_SmokeSensor102);
    lv_obj_set_width(ui_LabelValueMQ102, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValueMQ102, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelValueMQ102, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValueMQ102, "Value");

    ui_SmokeImg102 = lv_img_create(ui_SmokeSensor102);
    lv_img_set_src(ui_SmokeImg102, &ui_img_smoke_border_resize_png);
    lv_obj_set_width(ui_SmokeImg102, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_SmokeImg102, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_SmokeImg102, 0);
    lv_obj_set_y(ui_SmokeImg102, 100);
    lv_obj_set_align(ui_SmokeImg102, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SmokeImg102, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SmokeImg102, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SmokeImg102, 180);

    ui_Switch102 = lv_switch_create(ui_Screen102);
    lv_obj_set_width(ui_Switch102, 60);
    lv_obj_set_height(ui_Switch102, 30);
    lv_obj_set_x(ui_Switch102, 0);
    lv_obj_set_y(ui_Switch102, 65);
    lv_obj_set_align(ui_Switch102, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Switch102, lv_color_hex(0xF96429), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch102, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch102, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch102, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ButtonBack102 = lv_btn_create(ui_Screen102);
    lv_obj_set_width(ui_ButtonBack102, 40);
    lv_obj_set_height(ui_ButtonBack102, 30);
    lv_obj_set_x(ui_ButtonBack102, -130);
    lv_obj_set_y(ui_ButtonBack102, -100);
    lv_obj_set_align(ui_ButtonBack102, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonBack102, lv_color_hex(0x278B6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBack102, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgBack102 = lv_img_create(ui_ButtonBack102);
    lv_img_set_src(ui_ImgBack102, &ui_img_back_png);
    lv_obj_set_width(ui_ImgBack102, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgBack102, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgBack102, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBack102, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgBack102, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgBack102, 10);

    lv_obj_add_event_cb(ui_FireImg102, ui_event_FireImg102, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SmokeImg102, ui_event_SmokeImg102, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBack102, ui_event_ButtonBack102, LV_EVENT_ALL, NULL);

}
