// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen201_screen_init(void)
{
    ui_Screen201 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen201, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen201, lv_color_hex(0xBDDEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen201, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Screen201);
    lv_obj_set_width(ui_Panel5, 64);
    lv_obj_set_height(ui_Panel5, 32);
    lv_obj_set_x(ui_Panel5, 0);
    lv_obj_set_y(ui_Panel5, -100);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelScreen201 = lv_label_create(ui_Screen201);
    lv_obj_set_width(ui_LabelScreen201, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScreen201, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelScreen201, 0);
    lv_obj_set_y(ui_LabelScreen201, -100);
    lv_obj_set_align(ui_LabelScreen201, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScreen201, "201");
    lv_obj_set_style_text_font(ui_LabelScreen201, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FlameSensor201 = lv_obj_create(ui_Screen201);
    lv_obj_remove_style_all(ui_FlameSensor201);
    lv_obj_set_width(ui_FlameSensor201, 100);
    lv_obj_set_height(ui_FlameSensor201, 100);
    lv_obj_set_x(ui_FlameSensor201, -75);
    lv_obj_set_y(ui_FlameSensor201, -20);
    lv_obj_set_align(ui_FlameSensor201, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FlameSensor201, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FlameSensor201, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FlameSensor201, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FlameSensor201, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FlameSensor201, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FlameSensor201, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_FlameSensor201, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFL201 = lv_label_create(ui_FlameSensor201);
    lv_obj_set_width(ui_LabelFL201, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFL201, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelFL201, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelFL201, "Flame");

    ui_LabelValueFL201 = lv_label_create(ui_FlameSensor201);
    lv_obj_set_width(ui_LabelValueFL201, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValueFL201, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelValueFL201, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValueFL201, "Value");

    ui_FireImg201 = lv_img_create(ui_FlameSensor201);
    lv_img_set_src(ui_FireImg201, &ui_img_fire_border_resize_png);
    lv_obj_set_width(ui_FireImg201, 100);
    lv_obj_set_height(ui_FireImg201, 100);
    lv_obj_set_x(ui_FireImg201, 0);
    lv_obj_set_y(ui_FireImg201, 100);
    lv_obj_set_align(ui_FireImg201, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_FireImg201, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FireImg201, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_FireImg201, 180);

    ui_SmokeSensor201 = lv_obj_create(ui_Screen201);
    lv_obj_remove_style_all(ui_SmokeSensor201);
    lv_obj_set_width(ui_SmokeSensor201, 100);
    lv_obj_set_height(ui_SmokeSensor201, 103);
    lv_obj_set_x(ui_SmokeSensor201, 75);
    lv_obj_set_y(ui_SmokeSensor201, -20);
    lv_obj_set_align(ui_SmokeSensor201, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SmokeSensor201, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SmokeSensor201, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SmokeSensor201, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SmokeSensor201, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SmokeSensor201, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SmokeSensor201, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SmokeSensor201, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMQ201 = lv_label_create(ui_SmokeSensor201);
    lv_obj_set_width(ui_LabelMQ201, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMQ201, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelMQ201, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelMQ201, "Smoke");

    ui_LabelValueMQ201 = lv_label_create(ui_SmokeSensor201);
    lv_obj_set_width(ui_LabelValueMQ201, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelValueMQ201, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelValueMQ201, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelValueMQ201, "Value");

    ui_SmokeImg201 = lv_img_create(ui_SmokeSensor201);
    lv_img_set_src(ui_SmokeImg201, &ui_img_smoke_border_resize_png);
    lv_obj_set_width(ui_SmokeImg201, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_SmokeImg201, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_SmokeImg201, 0);
    lv_obj_set_y(ui_SmokeImg201, 100);
    lv_obj_set_align(ui_SmokeImg201, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_SmokeImg201, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SmokeImg201, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SmokeImg201, 180);

    ui_Switch201 = lv_switch_create(ui_Screen201);
    lv_obj_set_width(ui_Switch201, 60);
    lv_obj_set_height(ui_Switch201, 30);
    lv_obj_set_x(ui_Switch201, 0);
    lv_obj_set_y(ui_Switch201, 65);
    lv_obj_set_align(ui_Switch201, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Switch201, lv_color_hex(0xF96429), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch201, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch201, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch201, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ButtonBack201 = lv_btn_create(ui_Screen201);
    lv_obj_set_width(ui_ButtonBack201, 40);
    lv_obj_set_height(ui_ButtonBack201, 30);
    lv_obj_set_x(ui_ButtonBack201, -130);
    lv_obj_set_y(ui_ButtonBack201, -100);
    lv_obj_set_align(ui_ButtonBack201, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonBack201, lv_color_hex(0x278B6A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonBack201, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgBack201 = lv_img_create(ui_ButtonBack201);
    lv_img_set_src(ui_ImgBack201, &ui_img_back_png);
    lv_obj_set_width(ui_ImgBack201, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgBack201, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgBack201, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBack201, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgBack201, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgBack201, 10);

    lv_obj_add_event_cb(ui_FireImg201, ui_event_FireImg201, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SmokeImg201, ui_event_SmokeImg201, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonBack201, ui_event_ButtonBack201, LV_EVENT_ALL, NULL);

}
