// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: sqline_1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Home
void ui_Home_screen_init(void);
lv_obj_t *ui_Home;
lv_obj_t *ui_LbName;
lv_obj_t *ui_GroupBtn;
lv_obj_t *ui_GroupScroll;
void button_event_handler(lv_event_t *e);
void create_room_button(lv_obj_t *parent, int room_number, int x, int y);
// void ui_event_Btn101(lv_event_t * e);
lv_obj_t *ui_Btn101;
lv_obj_t *ui_Lb101;
// lv_obj_t * ui_Btn102;
// lv_obj_t * ui_Lb102;
// lv_obj_t * ui_Btn103;
// lv_obj_t * ui_Lb103;
// lv_obj_t * ui_Btn104;
// lv_obj_t * ui_Lb104;
// lv_obj_t * ui_Btn105;
// lv_obj_t * ui_Lb105;
// lv_obj_t * ui_Btn106;
// lv_obj_t * ui_Lb106;
// lv_obj_t * ui_Btn201;
// lv_obj_t * ui_Lb201;
// lv_obj_t * ui_Btn202;
// lv_obj_t * ui_Lb202;
// lv_obj_t * ui_Btn203;
// lv_obj_t * ui_Lb203;
// lv_obj_t * ui_Btn204;
// lv_obj_t * ui_Lb204;
// lv_obj_t * ui_Btn301;
// lv_obj_t * ui_Lb301;
// lv_obj_t * ui_Btn302;
// lv_obj_t * ui_Lb302;
// lv_obj_t * ui_Btn303;
// lv_obj_t * ui_Lb303;
// lv_obj_t * ui_Btn304;
// lv_obj_t * ui_Lb304;
// lv_obj_t * ui_Btn401;
// lv_obj_t * ui_Lb401;
lv_obj_t *ui_PanelTemp;
void ui_event_BtnAdd(lv_event_t *e);
lv_obj_t *ui_BtnAdd;
lv_obj_t *ui_LbAdd;
lv_obj_t *ui_TextAreaHome;
void ui_event_KeyboardHome(lv_event_t *e);
char ui_event_TextArea(lv_event_t *e);
lv_obj_t *ui_KeyboardHome;
lv_obj_t *ui_LbSOS;

// SCREEN: ui_Room
void ui_Room_screen_init(void);
lv_obj_t *ui_Room;
lv_obj_t *ui_LbRoom;
void ui_event_BtnBack(lv_event_t *e);
lv_obj_t *ui_BtnBack;
lv_obj_t *ui_ImgBack;
lv_obj_t *ui_ContainHumiTemp;
void ui_event_ArcHumi(lv_event_t *e);
lv_obj_t *ui_ArcHumi;
lv_obj_t *ui_ValHumi;
lv_obj_t *ui_LbHumi;
void ui_event_ArcTemp(lv_event_t *e);
lv_obj_t *ui_ArcTemp;
lv_obj_t *ui_ValTemp;
lv_obj_t *ui_LbTemp;
lv_obj_t *ui_ContainFire;
lv_obj_t *ui_ValSmoke;
lv_obj_t *ui_ValFire;
lv_obj_t *ui_ImgFire;
lv_obj_t *ui_ImgSmoke;
void ui_event_BtnSafe(lv_event_t *e);
lv_obj_t *ui_BtnSafe;
lv_obj_t *ui_LbSafe;
lv_obj_t *ui_Battery;
lv_obj_t *ui_LbBat;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

void button_event_handler(lv_event_t *e)
{
    // Chuyển sang màn hình mới
    lv_disp_load_scr(ui_Room);

    lv_obj_t *btn = lv_event_get_target(e);
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *obj = lv_event_get_target(e); // Lấy đối tượng phát sinh sự kiện

    if (code == LV_EVENT_CLICKED)
    {
        // Lấy label từ đối tượng nút
        lv_obj_t *label = lv_obj_get_child(obj, 0); // Lấy phần tử con đầu tiên (label)
        char *text = lv_label_get_text(label);      // Lấy nội dung text của label
        lv_label_set_text(ui_LbRoom, text);
    }
}
void create_room_button(lv_obj_t *parent, int room_number, int x, int y)
{
    // Tạo nút
    lv_obj_t *btn = lv_btn_create(parent);
    lv_obj_set_width(btn, 60);
    lv_obj_set_height(btn, 40);
    lv_obj_set_x(btn, x);
    lv_obj_set_y(btn, y);
    lv_obj_set_align(btn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(btn, lv_color_hex(0x1EA686), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(btn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Tạo label trên nút
    lv_obj_t *label = lv_label_create(btn);
    lv_obj_set_width(label, LV_SIZE_CONTENT);  // 1
    lv_obj_set_height(label, LV_SIZE_CONTENT); // 1
    lv_obj_set_align(label, LV_ALIGN_CENTER);

    // Chuyển đổi số phòng thành chuỗi và đặt làm text của label
    char room_str[10];
    snprintf(room_str, sizeof(room_str), "%d", room_number);
    lv_label_set_text(label, room_str);

    lv_obj_add_event_cb(btn, button_event_handler, LV_EVENT_CLICKED, NULL);
}
void ui_event_BtnAdd(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_keyboard_set_target(ui_KeyboardHome, ui_TextAreaHome);
        _ui_flag_modify(ui_KeyboardHome, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_TextAreaHome, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_BtnAdd, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_PanelTemp, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_KeyboardHome(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_READY)
    {
        _ui_flag_modify(ui_TextAreaHome, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_BtnAdd, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_KeyboardHome, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        createRoom(e);
        _ui_flag_modify(ui_PanelTemp, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
char ui_event_TextArea(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *obj = lv_event_get_target(e);
    if (code == LV_EVENT_VALUE_CHANGED)
    {
        const char * text = lv_textarea_get_text(obj);
        return text;
        // Tìm label liên quan và cập nhật nội dung của nó
        // lv_obj_t * label = (lv_obj_t *)lv_event_get_user_data(e);
        // lv_label_set_text(label, text);
    }

}
void ui_event_BtnBack(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        lv_disp_load_scr(ui_Home);
    }
}
void ui_event_ArcHumi(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        _ui_arc_set_text_value(ui_ValHumi, target, "", "%");
    }
}
void ui_event_ArcTemp(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        _ui_arc_set_text_value(ui_ValTemp, target, "", "");
        //_ui_flag_modify(ui_BtnSafe, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_BtnSafe(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        turnOffSOS(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Home_screen_init();
    ui_Room_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home);
}
