// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: sqline_1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void changeRoom(lv_event_t * e);
void createRoom(lv_event_t * e);
void turnOffSOS(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
