// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: sqline_1

#include "ui.h"

void ui_Room_screen_init(void)
{
    ui_Room = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Room, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Room, lv_color_hex(0xB8DFE9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Room, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbRoom = lv_label_create(ui_Room);
    lv_obj_set_width(ui_LbRoom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbRoom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LbRoom, 0);
    lv_obj_set_y(ui_LbRoom, -105);
    lv_obj_set_align(ui_LbRoom, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbRoom, "101");
    lv_obj_set_style_text_color(ui_LbRoom, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbRoom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LbRoom, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnBack = lv_btn_create(ui_Room);
    lv_obj_set_width(ui_BtnBack, 40);
    lv_obj_set_height(ui_BtnBack, 30);
    lv_obj_set_x(ui_BtnBack, -130);
    lv_obj_set_y(ui_BtnBack, -90);
    lv_obj_set_align(ui_BtnBack, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BtnBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgBack = lv_img_create(ui_BtnBack);
    lv_img_set_src(ui_ImgBack, &ui_img_back_png);
    lv_obj_set_width(ui_ImgBack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgBack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBack, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgBack, 70);

    ui_ContainHumiTemp = lv_obj_create(ui_Room);
    lv_obj_remove_style_all(ui_ContainHumiTemp);
    lv_obj_set_width(ui_ContainHumiTemp, 160);
    lv_obj_set_height(ui_ContainHumiTemp, 120);
    lv_obj_set_x(ui_ContainHumiTemp, -65);
    lv_obj_set_y(ui_ContainHumiTemp, 0);
    lv_obj_set_align(ui_ContainHumiTemp, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainHumiTemp, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_ContainHumiTemp, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_ContainHumiTemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainHumiTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainHumiTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ContainHumiTemp, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ContainHumiTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainHumiTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainHumiTemp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcHumi = lv_arc_create(ui_ContainHumiTemp);
    lv_obj_set_width(ui_ArcHumi, 70);
    lv_obj_set_height(ui_ArcHumi, 70);
    lv_obj_set_align(ui_ArcHumi, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcHumi, 50);
    lv_arc_set_bg_angles(ui_ArcHumi, 180, 0);

    lv_obj_set_style_arc_color(ui_ArcHumi, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHumi, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_flag(ui_ArcHumi, LV_OBJ_FLAG_ADV_HITTEST);

    ui_ValHumi = lv_label_create(ui_ArcHumi);
    lv_obj_set_width(ui_ValHumi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValHumi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ValHumi, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_ValHumi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ValHumi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(ui_ValHumi, "50%");

    ui_LbHumi = lv_label_create(ui_ContainHumiTemp);
    lv_obj_set_width(ui_LbHumi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbHumi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LbHumi, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_LbHumi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbHumi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(ui_LbHumi, "Humi");

    ui_ArcTemp = lv_arc_create(ui_ContainHumiTemp);
    lv_obj_set_width(ui_ArcTemp, 70);
    lv_obj_set_height(ui_ArcTemp, 70);
    // lv_obj_set_x(ui_ArcTemp, -34);
    // lv_obj_set_y(ui_ArcTemp, -1);
    lv_obj_set_align(ui_ArcTemp, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcTemp, 25);
    lv_arc_set_bg_angles(ui_ArcTemp, 180, 0);

    lv_obj_set_style_arc_color(ui_ArcTemp, lv_color_hex(0xC61313), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcTemp, lv_color_hex(0xFC8181), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemp, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    
    lv_obj_add_flag(ui_ArcTemp, LV_OBJ_FLAG_ADV_HITTEST);

    ui_ValTemp = lv_label_create(ui_ArcTemp);
    lv_obj_set_width(ui_ValTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ValTemp, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_ValTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ValTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(ui_ValTemp, "25");

    ui_LbTemp = lv_label_create(ui_ContainHumiTemp);
    lv_obj_set_width(ui_LbTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbTemp, LV_SIZE_CONTENT);    /// 1
    // lv_obj_set_x(ui_LbTemp, 0);
    // lv_obj_set_y(ui_LbTemp, -10);
    lv_obj_set_align(ui_LbTemp, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color( ui_LbTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LbTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(ui_LbTemp, "Temp");

    ui_ContainFire = lv_obj_create(ui_Room);
    lv_obj_remove_style_all(ui_ContainFire);
    lv_obj_set_width(ui_ContainFire, 90);
    lv_obj_set_height(ui_ContainFire, 120);
    lv_obj_set_x(ui_ContainFire, 86);
    lv_obj_set_y(ui_ContainFire, 0);
    lv_obj_set_align(ui_ContainFire, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainFire, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_ContainFire, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_clear_flag(ui_ContainFire, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainFire, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainFire, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ContainFire, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ContainFire, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainFire, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainFire, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValSmoke = lv_label_create(ui_ContainFire);
    lv_obj_set_width(ui_ValSmoke, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValSmoke, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ValSmoke, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValSmoke, "No");

    ui_ValFire = lv_label_create(ui_ContainFire);
    lv_obj_set_width(ui_ValFire, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValFire, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ValFire, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValFire, "No");

    ui_ImgFire = lv_img_create(ui_Room);
    lv_img_set_src(ui_ImgFire, &ui_img_fire_border_resize_png);
    lv_obj_set_width(ui_ImgFire, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgFire, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgFire, -80);
    lv_obj_set_y(ui_ImgFire, 90);
    lv_obj_set_align(ui_ImgFire, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgFire, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgFire, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgFire, 100);

    ui_ImgSmoke = lv_img_create(ui_Room);
    lv_img_set_src(ui_ImgSmoke, &ui_img_smoke_border_resize_png);
    lv_obj_set_width(ui_ImgSmoke, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgSmoke, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImgSmoke, 80);
    lv_obj_set_y(ui_ImgSmoke, 90);
    lv_obj_set_align(ui_ImgSmoke, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgSmoke, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgSmoke, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgSmoke, 100);

    ui_BtnSafe = lv_btn_create(ui_Room);
    lv_obj_set_width(ui_BtnSafe, 60);
    lv_obj_set_height(ui_BtnSafe, 40);
    lv_obj_set_x(ui_BtnSafe, 0);
    lv_obj_set_y(ui_BtnSafe, 90);
    lv_obj_set_align(ui_BtnSafe, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSafe, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_BtnSafe, lv_color_hex(0x349653), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSafe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbSafe = lv_label_create(ui_BtnSafe);
    lv_obj_set_width(ui_LbSafe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbSafe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LbSafe, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbSafe, "Off");

    ui_Battery = lv_btn_create(ui_Room);
    lv_bar_set_start_value(ui_Battery, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Battery, 50);
    lv_obj_set_height(ui_Battery, 40);
    lv_obj_set_x(ui_Battery, 120);
    lv_obj_set_y(ui_Battery, -90);
    lv_obj_set_align(ui_Battery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Battery, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_bg_color(ui_Battery, lv_color_hex(0x349653), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // lv_obj_set_style_radius(ui_Battery, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_color(ui_Battery, lv_color_hex(0xE3FB40), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_Battery, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LbBat = lv_label_create(ui_Battery);
    lv_obj_set_width(ui_LbBat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbBat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LbBat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbBat, "On");
    // lv_obj_set_style_text_color(ui_LbBat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_LbBat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnBack, ui_event_BtnBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcHumi, ui_event_ArcHumi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcTemp, ui_event_ArcTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSafe, ui_event_BtnSafe, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Battery, ui_event_Battery, LV_EVENT_ALL, NULL);

}
